### PR TITLE
Using filter_input over $_REQUEST

### PR DESCRIPTION
**Pull request by GooBall**
- Now using `filter_input` in place of `$_REQUEST`.
- Indentation corrections.

### CODE REVIEW

**Comment by jrha** [comment]
Squash 14613b6 and 35a9e1b?

**Comment by GooBall** [comment]
Sure - just added another commit too.

**Comment by jrha** [comment]
missing missing?

**Comment by jrha** [comment]
Merged manually in 87200ae032d92edfd660e83bbb516af9f0b0f32f

**Pull request closed without merging**
