### PR TITLE
Move from MySQL to MySQLi

### LINKED ISSUE #80: Migrate to MySQLi or PDO_MYSQL
The [classic PHP MySQL extension](http://php.net/manual/en/intro.mysql.php) was deprecated in PHP 5.5.0 and has been removed in PHP 7.0.0 so we should stop using it.

[We have two choices](http://php.net/manual/en/mysqlinfo.api.choosing.php) MySQLi may well be the simplest option.

### PR DESCRIPTION
**Pull request by GooBall**
Move from deprecated MySQL extension to MySQLi. Fixes #80

### CODE REVIEW

**Comment by jrha** [comment]
LGTM. Tested?

**Comment by GooBall** [comment]
Yep, all working my end.

**Comment by jrha** [comment]
Rebase!

**Comment by GooBall** [comment]
Done.

**Pull request merged**
